[package]
name = "json5-lua"
version = "0.1.0"
edition = "2021"

[lib]
name = "json5"
crate-type = ["cdylib"]

[dependencies]
serde_json = "=1.0.116"
json5 = "0.4.1"
mlua = { version = "0.9.7", features = ["luajit", "module", "serialize"] }
