name: Rust

on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: xpol/setup-lua@v0.3
      with:
        luaVersion: "luajit-2.0.5"
    - name: Build
      run: cargo build --verbose --release
      env:
        LUA_LIB: "./.lua/lib"
    - uses: actions/upload-artifact@v2
      with:
        name: json5.dll
        path: target/release/json5.dll
      
